server:
  port: 8080
spring:
  application:
    name: nacos-demo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.49.87:8848
        namespace: dev-d #指定nacos命名空间

    # 熔断限流
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8888

  main:
    allow-bean-definition-overriding: true #spring boot 2.1 需设置
dubbo:
  scan:
    base-packages: com.ncars.nacos.service
  protocol:
    name: dubbo #协议
    port: 20880
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    parameters[namespace]: ${spring.cloud.nacos.discovery.namespace}  #指定dubbo暴露服务的命名空间
  application:
    qos-enable: false #dubbo运维服务是否开启
  consumer:
    check: false #启动时就检查依赖的服务