server:
  port: 8080
spring:
  application:
    name: nacos-demo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.49.87:8848
  main:
    allow-bean-definition-overriding: true #spring boot 2.1 需设置
dubbo:
  scan:
    base-packages: com.ncars.nacos.service
  protocol:
    name: dubbo #协议
    port: 20880
  registry:
    address: nacos://39.107.49.87:8848
  application:
    qos-enable: false #dubbo运维服务是否开启
  consumer:
    check: false #启动时就检查依赖的服务