server:
  port: 8081
spring:
  application:
    name: nacos-demo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.49.87:8848 #注册中心地址
dubbo:
  registry:
    address: nacos://39.107.49.87:8848